@url = https://8080-eulaahsanto-aulagamessw-k1mwtkoqyjv.ws-us116.gitpod.io

GET {{url}}/plataformas
 
###
POST {{url}}/plataformas
Content-Type: application/json
 
{
    "nome": "Xbox"
}
 

###
GET {{url}}/plataformas/8